### ISSUE TITLE
Howto create Tunnel with ssh password

### ISSUE THREAD

**Issue by g----** [lordmauve/chopsticks#54]
Hi, I have SSH username and password - is there currently _any_ way how to authenticate ssh tunnel with password? I don't know - overriding something, creating some objects by myself, etc? I'd really need to pass the password to connect. Any hints would be useful.

Thanks

**Comment by lordmauve** [comment]
Chopsticks has no plans to support password authentication. The solution is always to use password-less SSH, ie. by using your password to set up a cryptographic identity.

Issue #45 tracks writing some documentation about how to do this, but [a basic configuration would be a little like this][(https://michaellindon.github.io/lindonslog/linux-unix/ssh-keygen-keys/), and takes about 5 minutes to set up.

**Comment by meshy** [comment]
One of the things that I would hope to configure on a server would be passwordless SSH, and chopsticks seems like it would be a great tool for setting up servers in that way.

Having no way to authenticate with a password means that that first step needs to be done manually. Is there any possible workaround for this that would allow for chopsticks to be used for that initial bootstrap step?

**Comment by meshy** [comment]
I'm sorry, I should have read your link before posting.

It looks like this can be done with a simple `ssh-copy-id` command before commencing -- that's good enough for my purposes `:)`

**Comment by lordmauve** [comment]
Many cloud providers can be configured to drop your SSH identity on all newly created hosts. Because cryptographic authentication is commonplace, and more secure in any case, in my opinion password authentication is not a feature that is important enough, these days, to justify investing time in. I'm also scared of it - I think it's relatively difficult to trick the SSH password prompt into having a dialogue with the Chopsticks process, and it risks being brittle and non-portable even if we succeed.

**Comment by lordmauve** [comment]
According to [stack exchange](https://unix.stackexchange.com/questions/38737/ssh-login-with-clear-text-password-as-a-parameter), if you really must do this there's a ``sshpass`` program that looks like it would be easy to wrap into a Chopsticks tunnel.
